package com.mg.community.mapper;

import com.mg.community.model.Sysparam;
import com.mg.community.model.SysparamExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysparamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysparam
     *
     * @mbg.generated Sat Feb 08 12:31:53 CST 2020
     */
    long countByExample(SysparamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysparam
     *
     * @mbg.generated Sat Feb 08 12:31:53 CST 2020
     */
    int deleteByExample(SysparamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysparam
     *
     * @mbg.generated Sat Feb 08 12:31:53 CST 2020
     */
    int insert(Sysparam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysparam
     *
     * @mbg.generated Sat Feb 08 12:31:53 CST 2020
     */
    int insertSelective(Sysparam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysparam
     *
     * @mbg.generated Sat Feb 08 12:31:53 CST 2020
     */
    List<Sysparam> selectByExample(SysparamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysparam
     *
     * @mbg.generated Sat Feb 08 12:31:53 CST 2020
     */
    int updateByExampleSelective(@Param("record") Sysparam record, @Param("example") SysparamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysparam
     *
     * @mbg.generated Sat Feb 08 12:31:53 CST 2020
     */
    int updateByExample(@Param("record") Sysparam record, @Param("example") SysparamExample example);
}