CREATE TABLE NOTIFICATION
(
	ID BIGINT AUTO_INCREMENT,
	NOTIFIER BIGINT NOT NULL,
	RECEIVER BIGINT NOT NULL,
	TYPE INT NOT NULL,
	OUTERID BIGINT NOT NULL,
	STATUS INT DEFAULT 0 NOT NULL,
	GMT_CREATE BIGINT NOT NULL,
	CONSTRAINT NOTIFICATION_PK
		PRIMARY KEY (ID)
);

COMMENT ON TABLE NOTIFICATION IS '通知表';

COMMENT ON COLUMN NOTIFICATION.NOTIFIER IS '通知者';

COMMENT ON COLUMN NOTIFICATION.RECEIVER IS '接受通知者';

COMMENT ON COLUMN NOTIFICATION.TYPE IS '通知类型';

COMMENT ON COLUMN NOTIFICATION.OUTERID IS '通知类型对应ID';

COMMENT ON COLUMN NOTIFICATION.STATUS IS '状态';

